export const fotoImages =[
    require('../../assets/Foto1.png'),
    require('../../assets/Foto2.png'),
    require('../../assets/Foto3.png'),
    require('../../assets/Foto4.png'),
    require('../../assets/Foto5.png'),
    require('../../assets/Foto6.png'),
    require('../../assets/Foto7.png'),
    require('../../assets/Foto8.png'),
    require('../../assets/Foto9.png'),
    require( '../../assets/Foto10.png'),
    require( '../../assets/Foto11.png'),
    require( '../../assets/Foto12.png'),
    require( '../../assets/Foto13.png'),
    require( '../../assets/Foto14.png'),
    require( '../../assets/Foto15.png'),
    require( '../../assets/Foto16.png'),
    require( '../../assets/Foto17.png'),
    require( '../../assets/Foto18.png'),
    require( '../../assets/Foto19.png'),
    require( '../../assets/Foto20.png'),
    require( '../../assets/Foto21.png'),
    require( '../../assets/Foto22.png'),
    require( '../../assets/Foto23.png'),
    require( '../../assets/Foto24.png'),
];

export const numberImages=[
    require('../../assets/1.png'),
    require('../../assets/2.png'),
    require('../../assets/3.png'),
    require('../../assets/4.png'),
    require('../../assets/5.png'),
    require('../../assets/6.png'),
    require('../../assets/7.png'),
    require('../../assets/8.png'),
    require('../../assets/9.png'),
    require( '../../assets/10.png'),
    require( '../../assets/11.png'),
    require( '../../assets/12.png'),
    require( '../../assets/13.png'),
    require( '../../assets/14.png'),
    require( '../../assets/15.png'),
    require( '../../assets/16.png'),
    require( '../../assets/17.png'),
    require( '../../assets/18.png'),
    require( '../../assets/19.png'),
    require( '../../assets/20.png'),
    require( '../../assets/21.png'),
    require( '../../assets/22.png'),
    require( '../../assets/23.png'),
    require( '../../assets/24.png'),
]